export { default as OrganismOffer } from "./OrganismOffer";
export { default as OrganismHero } from "./OrganismHero";
export { default as OrganismDescription } from "./OrganismDescription";
export { default as OrganismCons } from "./OrganismCons";
export { default as OrganismPricing } from "./OrganismPricing";
export { default as OrganismContact } from "./OrganismContact";
export { default as OrganismFooter } from "./OrganismFooter";
export { default as OrganismModalFB } from "./OrganismModalFB";
export { default as OrganismFAQ } from "./OrganismFAQ";
